services:
  api:
    container_name: api
    build: .
    restart: always
    ports:
      # - 8081:5000
      - 5000:5000
    # depends_on:
    #   - pg
    #   - redis
    env_file:
      - ./.env
    volumes:
      - ./storage:/home/app/storage
